"""Vault__Publish__Api_Docs — api/openapi.json + api/docs/ (P4b, 08).

Two artefacts with very different costs:
  api/openapi.json  — a few KB, generated from the same enumeration that
                      feeds manifest.json, so it cannot drift. Describes ONLY
                      what this folder actually serves: GET, no auth,
                      ciphertext responses. servers is relative (".") so the
                      file works on any host under any path prefix.
  api/docs/         — Swagger UI. CDN mode emits ~4 KB of HTML pinned with
                      SRI; bundled mode vendors the verified files (+1.53 MB).

SP-11: the CSP <meta> on the docs page is MANDATORY — the page shares an
origin with a loader that may hold a reader's key; `connect-src 'self'` is
the exfiltration backstop even for a script that somehow executed.

Deviation from the pack's file list, on purpose: no Schema__OpenAPI_Document
Type_Safe class is defined. OpenAPI is an externally-specified nested-map
format; modelling it as Type_Safe fields adds no type safety over emitting
the document directly from the enumeration, and would have to be relaxed on
every OpenAPI addition. Raised in the phase report.
"""
import json

from sgit_ai._version                              import VERSION
from sgit_ai.core.Vault__Sync__Base                import Vault__Sync__Base
from sgit_ai.network.assets.Swagger_UI__Assets     import (SWAGGER_UI_FILES, SWAGGER_UI_VERSION,
                                                           Swagger_UI__Assets)
from sgit_ai.safe_types.Enum__Api_Docs_Mode        import Enum__Api_Docs_Mode

CDN_BASE = f'https://cdn.jsdelivr.net/npm/swagger-ui-dist@{SWAGGER_UI_VERSION}'

CSP_CDN     = ("default-src 'none'; script-src 'self' https://cdn.jsdelivr.net; "
               "style-src 'self' https://cdn.jsdelivr.net 'unsafe-inline'; "
               "img-src 'self' data:; connect-src 'self'")
CSP_BUNDLED = ("default-src 'none'; script-src 'self'; "
               "style-src 'self' 'unsafe-inline'; "
               "img-src 'self' data:; connect-src 'self'")


class Vault__Publish__Api_Docs(Vault__Sync__Base):

    def build(self, vault_id: str, objects: list, mode: str = None) -> dict:
        """{relative_path: bytes} to add to the plaintext surface.

        objects is the (file_id, size, sha256) enumeration manifest.json is
        built from — the openapi examples are REAL file ids of this publish.
        """
        files = {'api/openapi.json': self._openapi_bytes(vault_id, objects)}
        if mode:
            docs_mode = Enum__Api_Docs_Mode(mode)
            # CSP forbids inline script (script-src has no 'unsafe-inline'),
            # so the UI init lives in a same-origin file.
            files['api/docs/init.js'] = (
                b"if (window.SwaggerUIBundle) {\n"
                b"  window.ui = SwaggerUIBundle({ url: '../openapi.json', dom_id: '#swagger-ui' });\n"
                b"}\n")
            if docs_mode == Enum__Api_Docs_Mode.CDN:
                files['api/docs/index.html'] = self._docs_page_cdn().encode('utf-8')
            else:
                assets = Swagger_UI__Assets().get_files()
                for name, data in assets.items():
                    files[f'api/docs/{name}'] = data
                files['api/docs/index.html'] = self._docs_page_bundled().encode('utf-8')
        return files

    # --- openapi.json -------------------------------------------------------

    def _openapi_bytes(self, vault_id: str, objects: list) -> bytes:
        examples = self._real_examples(objects)
        document = {
            'openapi': '3.1.0',
            'info': {
                'title'      : f'sgit vault {vault_id} (static projection)',
                'version'    : '1',
                'description': 'A published, read-only vault. Every response is ciphertext; '
                               'this host holds no key and can decrypt nothing. '
                               f'Generated by sgit {VERSION} from manifest.json.',
            },
            'servers': [{'url': '.'}],                   # relative: any host, any path prefix
            'paths': {
                '/api/vault/read/{vault_id}/{file_id}': {
                    'get': {
                        'summary': 'Fetch one encrypted object',
                        'parameters': [
                            {'name': 'vault_id', 'in': 'path', 'required': True,
                             'schema': {'type': 'string', 'const': vault_id}},
                            {'name': 'file_id', 'in': 'path', 'required': True,
                             'schema': {'type': 'string'},
                             'examples': examples},
                        ],
                        'responses': {
                            '200': {'description': 'Opaque ciphertext (AES-256-GCM: IV(12)‖ct‖tag(16))',
                                    'content': {'application/octet-stream':
                                                {'schema': {'type': 'string', 'format': 'binary'}}}},
                            '404': {'description': 'No such object'},
                        },
                    },
                },
                '/manifest.json': {'get': {'summary': 'Published object list, commit list, and the '
                                                      'declared plaintext surface',
                                           'responses': {'200': {'description': 'The manifest'}}}},
                '/cover.json':    {'get': {'summary': 'Public description of this vault',
                                           'responses': {'200': {'description': 'The cover'}}}},
            },
        }
        return (json.dumps(document, indent=2, ensure_ascii=False) + '\n').encode('utf-8')

    def _real_examples(self, objects: list) -> dict:
        """Three REAL objects (ref, index, data) so 'Try it out' works — never
        the full enumeration, which would duplicate manifest.json unbounded."""
        examples = {}
        for label, prefix in (('the head ref',     'bare/refs/'),
                              ('the branch index', 'bare/indexes/'),
                              ('an object',        'bare/data/')):
            match = next((fid for fid, _size, _sha in objects if fid.startswith(prefix)), None)
            if match:
                examples[label] = {'value': match}
        return examples or {'the manifest': {'value': 'manifest.json'}}

    # --- docs pages ---------------------------------------------------------

    def _docs_page_cdn(self) -> str:
        css = SWAGGER_UI_FILES['swagger-ui.css']
        js  = SWAGGER_UI_FILES['swagger-ui-bundle.js']
        return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="{CSP_CDN}">
<title>Vault API docs</title>
<link rel="stylesheet" href="{CDN_BASE}/swagger-ui.css"
      integrity="{css}"
      crossorigin="anonymous" referrerpolicy="no-referrer">
</head>
<body>
<div id="swagger-ui">
  <p>Loading API docs… If this page stays empty the CDN is unreachable —
  the contract is still readable at <a href="../openapi.json">./openapi.json</a>,
  and the vault itself clones fine without it.</p>
</div>
<script src="{CDN_BASE}/swagger-ui-bundle.js"
        integrity="{js}"
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="init.js"></script>
</body>
</html>
"""

    def _docs_page_bundled(self) -> str:
        return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="{CSP_BUNDLED}">
<title>Vault API docs</title>
<link rel="stylesheet" href="swagger-ui.css">
</head>
<body>
<div id="swagger-ui">
  <p>Loading API docs… The contract is also readable at
  <a href="../openapi.json">./openapi.json</a>.</p>
</div>
<script src="swagger-ui-bundle.js"></script>
<script src="init.js"></script>
</body>
</html>
"""
